### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by ilanbiala** [yhsiang/tabular#1]
Can we get some better documentation, such as screenshots and examples and API?

**Comment by nathancooper** [comment]
I agree, some documentation and especially a screenshot will be helpful. I don't know if this is working as intended.

**Comment by slestak** [comment]
Same here.  I have a csv file that does not appear to change in any helpful way when I set the grammar to CSV.

**Comment by robertkuerzinger** [comment]
At least some starting documentation would be great, yep.
I dropped a CSV file after installing the package, and it's being displayed the same way as before ...

**Comment by yhsiang** [comment]
sorry for noticing this so late, I will find some time to solve this

**Comment by rossshannon** [comment]
Yes, this doesn’t seem to work at the moment.

**Comment by ilanbiala** [comment]
Closing this because it makes more sense to choose a more active package.
